### ISSUE TITLE
`listen` section of hello world of docs doesn't have `listen` in the snippet

### ISSUE THREAD

**Issue by MonstraG** [RockstarLang/rockstar2#12]
It reads:
> To read a line of input from `STDIN`, use the `listen` keyword. To read a line into a variable, use `listen to <variable>`:
```rockstar
Roll outside into the value
Until the value is nothing
Shout the value
Roll outside into the value
```

There is no `listen`, and the code doesn't do what it's supposed to I think? (I'm not a rockstar developer yet).

Last time this snippet was modified in commit [c94fcd8e](https://github.com/MonstraG/rockstar2/commit/c94fcd8ea95c7ea72ab0de4d226362ee64883afc) and it used to be
```
Listen to the night.
Whisper the night.
```

Which seems to be more correct.

**Comment by dylanbeattie** [comment]
Fixed in https://github.com/RockstarLang/rockstar2/pull/13
