### ISSUE TITLE
Latest prebuilt binary version differs from binary version when built from source

### ISSUE THREAD

**Issue by Yewzir** [RockstarLang/rockstar2#2]
The prebuilt binary version is either displayed as `Rockstar v0.9.1 on linux-musl-x64.` or `v0.9.1`, depending on whether one enters the REPL or [only](https://github.com/RockstarLang/rockstar2/issues/1) supplies the `--version` command-line argument. That's expected behavior. However, doing the same thing with binaries that are built from source results in either `Rockstar v42.42.42-development on linux-musl-x64.`  or `v42.42.42-development` being displayed. Now, that's kind of an issue. The source stems from the release/tag section that is explicitly marked as `v0.9.1`. In my opinion, it makes little to no sense for you to prebuild and pack archives with one version, and modify it to a _development_ version when packing source archives. If it were a git clone of a master/dev branch, or an archive that's advertised as such, then I have nothing to say and fully understand. In this case, not so much especially since the build process must run completely unattended, for our purposes.

Regards
@Yewzir

**Comment by dylanbeattie** [comment]
The version is actually patched as part of the Windows/macOS/Linux build steps - so it's always hardwired to 42.42.42 in source. But you're right, it should be consistent: I'll look at patching the version of the source that's used to publish the corresponding ZIP archives as well. Thanks :)

**Comment by Yewzir** [comment]
> The version is actually patched as part of the Windows/macOS/Linux build steps - so it's always hardwired to 42.42.42 in source. But you're right, it should be consistent: I'll look at patching the version of the source that's used to publish the corresponding ZIP archives as well. Thanks :)

I didn't know that, and instantly assuming you were doing such a modification afterwards was plain wrong. For that, I apologize.

**Comment by Yewzir** [comment]
Thank you.
