### ISSUE TITLE
Arrays are always falsy

### ISSUE THREAD

**Issue by duckyluuk** [RockstarLang/rockstar2#5]
The docs state that only `false`, `null`, `mysterious`, `""`, and `0` [are falsy](https://beta.codewithrockstar.com/docs/05-boolean-logic.html). 
However, Arrays are also evaluated as falsy, both empty and full.
See the following examples:
![image](https://github.com/user-attachments/assets/7d6ae640-243e-4535-b98a-731ed5128f56)

This should probably either be documented, or they should be evaluated to a truthy. 
Perhaps evaluating an empty array to a falsy and a non-empty array to a truthy makes even more sense?

**Comment by dylanbeattie** [comment]
Good spot. I've modified the code so that empty arrays are false, any array with list or hash elements is true, and updated the docs. Thank you!
